### ISSUE TITLE
[bug] Current workflow artifacts are not being removed.

### ISSUE THREAD

**Issue by T145** [jimschubert/delete-artifacts-action#1]
Reference the following:

- https://github.com/T145/black-mirror/runs/3905900879?check_suite_focus=true
- https://github.com/T145/black-mirror/actions/runs/1345867691

I'm expecting the artifacts produced during the workflow runtime to be deleted, but they are not. Configuration is here:

- https://github.com/T145/black-mirror/blob/master/.github/workflows/publish_release.yml#L129

**Comment by jimschubert** [comment]
@T145 what are you referencing to indicate the artifacts have not been deleted? Your referenced workflow shows the artifact was deleted in logs and also via GitHub UI.

![Screenshot_20211017-221553](https://user-images.githubusercontent.com/109659/137659258-cd941cb5-49cf-4ab9-b079-df28b0763689.jpg)

**Comment by T145** [comment]
![artifacts](https://user-images.githubusercontent.com/1214129/137663733-29205526-f3eb-4ee3-9a4d-eb3ddb4bb67f.png)
These do not seem to be deleted.

**Comment by HunterAhlquist** [comment]
Same here, they appear to not be deleted and are filling up my storage. It errors out despite reporting as successful: "Failed to run the action."
This is my yaml:
```yaml
name: Weekly cleanup

on:
  workflow_dispatch:
  schedule:
    - cron: "0 18 * * 6"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Weekly Artifact Cleanup
        uses: jimschubert/delete-artifacts-action@v1
        with:
          log_level: 'error'
          min_bytes: '0'
```
